packages:
  - packages/*
  - examples/*

ignoredBuiltDependencies:
  - cpu-features
  - protobufjs
  - ssh2

minimumReleaseAge: 4320

onlyBuiltDependencies:
  - "@bufbuild/buf"
  - esbuild
  - lefthook
  - msw

strictDepBuilds: true

trustPolicy: no-downgrade
