packages:
  - packages/*

ignoredBuiltDependencies:
  - protobufjs

minimumReleaseAge: 4320

onlyBuiltDependencies:
  - "@bufbuild/buf"
  - esbuild
  - lefthook
  - msw

strictDepBuilds: true

trustPolicy: no-downgrade
