// Generated by ts-to-zod
import { z } from "zod";
import {
  type AnyValue,
  type ArrayValue,
  type KeyValueList,
  type KeyValue,
  type InstrumentationScope,
  type Resource,
  type TracesData,
  type ResourceSpans,
  type ScopeSpans,
  type Span,
  type Span_Event,
  type Span_Link,
  type LogsData,
  type ResourceLogs,
  type ScopeLogs,
  type LogRecord,
  type Summary,
  type SummaryDataPoint,
  SpanFlags,
  SpanKind,
  StatusCode,
  SeverityNumber,
  LogRecordFlags,
  AggregationTemporality,
  DataPointFlags,
} from "./otlp-generated.js";

export const entityRefSchema = z.object({
  schemaUrl: z.union([z.string(), z.undefined()]).optional(),
  type: z.union([z.string(), z.undefined()]).optional(),
  idKeys: z.union([z.array(z.string()), z.undefined()]).optional(),
  descriptionKeys: z.union([z.array(z.string()), z.undefined()]).optional(),
});

export const spanFlagsSchema = z.enum(SpanFlags);

export const spanKindSchema = z.enum(SpanKind);

export const statusCodeSchema = z.enum(StatusCode);

export const severityNumberSchema = z.enum(SeverityNumber);

export const logRecordFlagsSchema = z.enum(LogRecordFlags);

export const aggregationTemporalitySchema = z.enum(AggregationTemporality);

export const dataPointFlagsSchema = z.enum(DataPointFlags);

export const exponentialHistogramDataPointBucketsSchema = z.object({
  offset: z.union([z.number(), z.undefined()]).optional(),
  bucketCounts: z.union([z.array(z.string()), z.undefined()]).optional(),
});

export const summaryDataPointValueAtQuantileSchema = z.object({
  quantile: z.union([z.number(), z.undefined()]).optional(),
  value: z.union([z.number(), z.undefined()]).optional(),
});

export const statusSchema = z.object({
  message: z.union([z.string(), z.undefined()]).optional(),
  code: z.union([statusCodeSchema, z.undefined()]).optional(),
});

export const anyValueSchema: z.ZodSchema<AnyValue> = z.lazy(() =>
  z.object({
    stringValue: z.union([z.string(), z.undefined()]).optional(),
    boolValue: z.union([z.boolean(), z.undefined()]).optional(),
    intValue: z.union([z.number(), z.undefined()]).optional(),
    doubleValue: z.union([z.number(), z.undefined()]).optional(),
    arrayValue: z.union([arrayValueSchema, z.undefined()]).optional(),
    kvlistValue: z.union([keyValueListSchema, z.undefined()]).optional(),
    bytesValue: z.union([z.string(), z.undefined()]).optional(),
  })
);

export const arrayValueSchema: z.ZodSchema<ArrayValue> = z.lazy(() =>
  z.object({
    values: z.union([z.array(anyValueSchema), z.undefined()]).optional(),
  })
);

export const keyValueListSchema: z.ZodSchema<KeyValueList> = z.lazy(() =>
  z.object({
    values: z.union([z.array(keyValueSchema), z.undefined()]).optional(),
  })
);

export const keyValueSchema: z.ZodSchema<KeyValue> = z.lazy(() =>
  z.object({
    key: z.union([z.string(), z.undefined()]).optional(),
    value: z.union([anyValueSchema, z.undefined()]).optional(),
  })
);

export const instrumentationScopeSchema: z.ZodSchema<InstrumentationScope> =
  z.lazy(() =>
    z.object({
      name: z.union([z.string(), z.undefined()]).optional(),
      version: z.union([z.string(), z.undefined()]).optional(),
      attributes: z.union([z.array(keyValueSchema), z.undefined()]).optional(),
      droppedAttributesCount: z.union([z.number(), z.undefined()]).optional(),
    })
  );

export const resourceSchema: z.ZodSchema<Resource> = z.lazy(() =>
  z.object({
    attributes: z.union([z.array(keyValueSchema), z.undefined()]).optional(),
    droppedAttributesCount: z.union([z.number(), z.undefined()]).optional(),
    entityRefs: z.union([z.array(entityRefSchema), z.undefined()]).optional(),
  })
);

export const tracesDataSchema: z.ZodSchema<TracesData> = z.lazy(() =>
  z.object({
    resourceSpans: z
      .union([z.array(resourceSpansSchema), z.undefined()])
      .optional(),
  })
);

export const resourceSpansSchema: z.ZodSchema<ResourceSpans> = z.lazy(() =>
  z.object({
    resource: z.union([resourceSchema, z.undefined()]).optional(),
    scopeSpans: z.union([z.array(scopeSpansSchema), z.undefined()]).optional(),
    schemaUrl: z.union([z.string(), z.undefined()]).optional(),
  })
);

export const scopeSpansSchema: z.ZodSchema<ScopeSpans> = z.lazy(() =>
  z.object({
    scope: z.union([instrumentationScopeSchema, z.undefined()]).optional(),
    spans: z.union([z.array(spanSchema), z.undefined()]).optional(),
    schemaUrl: z.union([z.string(), z.undefined()]).optional(),
  })
);

export const spanSchema: z.ZodSchema<Span> = z.lazy(() =>
  z.object({
    traceId: z.union([z.string(), z.undefined()]).optional(),
    spanId: z.union([z.string(), z.undefined()]).optional(),
    traceState: z.union([z.string(), z.undefined()]).optional(),
    parentSpanId: z.union([z.string(), z.undefined()]).optional(),
    flags: z.union([z.number(), z.undefined()]).optional(),
    name: z.union([z.string(), z.undefined()]).optional(),
    kind: z.union([spanKindSchema, z.undefined()]).optional(),
    startTimeUnixNano: z.union([z.string(), z.undefined()]).optional(),
    endTimeUnixNano: z.union([z.string(), z.undefined()]).optional(),
    attributes: z.union([z.array(keyValueSchema), z.undefined()]).optional(),
    droppedAttributesCount: z.union([z.number(), z.undefined()]).optional(),
    events: z.union([z.array(spanEventSchema), z.undefined()]).optional(),
    droppedEventsCount: z.union([z.number(), z.undefined()]).optional(),
    links: z.union([z.array(spanLinkSchema), z.undefined()]).optional(),
    droppedLinksCount: z.union([z.number(), z.undefined()]).optional(),
    status: z.union([statusSchema, z.undefined()]).optional(),
  })
);

export const spanEventSchema: z.ZodSchema<Span_Event> = z.lazy(() =>
  z.object({
    timeUnixNano: z.union([z.string(), z.undefined()]).optional(),
    name: z.union([z.string(), z.undefined()]).optional(),
    attributes: z.union([z.array(keyValueSchema), z.undefined()]).optional(),
    droppedAttributesCount: z.union([z.number(), z.undefined()]).optional(),
  })
);

export const spanLinkSchema: z.ZodSchema<Span_Link> = z.lazy(() =>
  z.object({
    traceId: z.union([z.string(), z.undefined()]).optional(),
    spanId: z.union([z.string(), z.undefined()]).optional(),
    traceState: z.union([z.string(), z.undefined()]).optional(),
    attributes: z.union([z.array(keyValueSchema), z.undefined()]).optional(),
    droppedAttributesCount: z.union([z.number(), z.undefined()]).optional(),
    flags: z.union([z.number(), z.undefined()]).optional(),
  })
);

export const logsDataSchema: z.ZodSchema<LogsData> = z.lazy(() =>
  z.object({
    resourceLogs: z
      .union([z.array(resourceLogsSchema), z.undefined()])
      .optional(),
  })
);

export const resourceLogsSchema: z.ZodSchema<ResourceLogs> = z.lazy(() =>
  z.object({
    resource: z.union([resourceSchema, z.undefined()]).optional(),
    scopeLogs: z.union([z.array(scopeLogsSchema), z.undefined()]).optional(),
    schemaUrl: z.union([z.string(), z.undefined()]).optional(),
  })
);

export const scopeLogsSchema: z.ZodSchema<ScopeLogs> = z.lazy(() =>
  z.object({
    scope: z.union([instrumentationScopeSchema, z.undefined()]).optional(),
    logRecords: z.union([z.array(logRecordSchema), z.undefined()]).optional(),
    schemaUrl: z.union([z.string(), z.undefined()]).optional(),
  })
);

export const logRecordSchema: z.ZodSchema<LogRecord> = z.lazy(() =>
  z.object({
    timeUnixNano: z.union([z.string(), z.undefined()]).optional(),
    observedTimeUnixNano: z.union([z.string(), z.undefined()]).optional(),
    severityNumber: z.union([severityNumberSchema, z.undefined()]).optional(),
    severityText: z.union([z.string(), z.undefined()]).optional(),
    body: z.union([anyValueSchema, z.undefined()]).optional(),
    attributes: z.union([z.array(keyValueSchema), z.undefined()]).optional(),
    droppedAttributesCount: z.union([z.number(), z.undefined()]).optional(),
    flags: z.union([z.number(), z.undefined()]).optional(),
    traceId: z.union([z.string(), z.undefined()]).optional(),
    spanId: z.union([z.string(), z.undefined()]).optional(),
    eventName: z.union([z.string(), z.undefined()]).optional(),
  })
);

export const summarySchema: z.ZodSchema<Summary> = z.lazy(() =>
  z.object({
    dataPoints: z
      .union([z.array(summaryDataPointSchema), z.undefined()])
      .optional(),
  })
);

export const summaryDataPointSchema: z.ZodSchema<SummaryDataPoint> = z.lazy(
  () =>
    z.object({
      attributes: z.union([z.array(keyValueSchema), z.undefined()]).optional(),
      startTimeUnixNano: z.union([z.string(), z.undefined()]).optional(),
      timeUnixNano: z.union([z.string(), z.undefined()]).optional(),
      count: z.union([z.string(), z.undefined()]).optional(),
      sum: z.union([z.number(), z.undefined()]).optional(),
      quantileValues: z
        .union([z.array(summaryDataPointValueAtQuantileSchema), z.undefined()])
        .optional(),
      flags: z.union([z.number(), z.undefined()]).optional(),
    })
);
