import z from "zod";

export const problemDetailsSchema = z.object({
  type: z
    .url()
    .default("about:blank")
    .describe("URI reference identifying the problem type"),
  status: z
    .number()
    .int()
    .min(100)
    .max(599)
    .optional()
    .describe("HTTP status code generated by the origin server"),
  title: z
    .string()
    .optional()
    .describe("Short human-readable summary of the problem type"),
  detail: z
    .string()
    .optional()
    .describe("Human-readable explanation specific to this occurrence"),
  instance: z
    .string()
    .optional()
    .describe("URI reference identifying this specific occurrence"),
});

export type SignalsApiErrorResponse = z.infer<typeof problemDetailsSchema>;
